networks:
  bdCluster:
    name: bdCluster
    driver: ipvlan
    external: true
    driver_opts:
      parent: ${ETHERNET_NAME}
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24
          gateway: 192.168.1.1

services:
  registry:
    image: registry:2
    hostname: registry.bdc.home
    container_name: registry
    networks:
      bdCluster:
        ipv4_address: 192.168.1.23
    environment:
      TZ: Asia/Kolkata
      REGISTRY_VALIDATION_DISABLED: "true"
    # ports:
    #   - 5000:5000
    volumes:
      - ${LOCAL_DIR}docker/registry-data:/var/lib/registry:z
    restart: unless-stopped
