[dns]
    # Array of custom DNS records
    # Example: hosts = [ "127.0.0.1 mylocal", "192.168.0.1 therouter" ]
    #
    # Possible values are:
    #     Array of custom DNS records each one in HOSTS form: "IP HOSTNAME"

    hosts = [
        "192.168.1.11 pihole.bdc.home",
        "192.168.1.12 worker1.bdc.home",
        "192.168.1.13 worker2.bdc.home",
        "192.168.1.14 worker3.bdc.home",
        "192.168.1.15 unbound.bdc.home",
        "192.168.1.21 postgresql.bdc.home",
        "192.168.1.26 redis.bdc.home",
        "192.168.1.31 nessie.bdc.home",
        "192.168.1.32 hue.bdc.home",
        "192.168.1.33 trino-co.bdc.home",
        "192.168.1.34 airflow.bdc.home",
        "192.168.1.35 kafka-sr.bdc.home",
        "192.168.1.36 ksqldb.bdc.home",
        "192.168.1.37 kconcen.bdc.home",
        "192.168.1.40 pystream.bdc.home",
        "192.168.1.41 trino-wk1.bdc.home",
        "192.168.1.42 trino-wk2.bdc.home",
        "192.168.1.43 trino-wk3.bdc.home",
        "192.168.1.51 kafka-1.bdc.home",
        "192.168.1.52 kafka-2.bdc.home",
        "192.168.1.53 kafka-3.bdc.home",
        "192.168.1.91 name-res1.bdc.home",
        "192.168.1.92 name-res2.bdc.home",
        "192.168.1.93 name-res3.bdc.home",
        "192.168.1.94 secon-hist.bdc.home",
        "192.168.1.95 zookeeper-1.bdc.home",
        "192.168.1.96 zookeeper-2.bdc.home",
        "192.168.1.97 zookeeper-3.bdc.home",
        "192.168.1.101 data-node1.bdc.home",
        "192.168.1.102 data-node2.bdc.home",
        "192.168.1.103 data-node3.bdc.home",
        "192.168.1.201 jupyter.bdc.home"
    ]
