networks:
  ph_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
          ip_range: 192.168.100.2/32
  bdCluster:
    name: bdCluster
    driver: ipvlan
    driver_opts:
      parent: wlo1
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24
          gateway: 192.168.1.1

services:
  # bind9:
  #   container_name: bind9
  #   image: ubuntu/bind9:latest
  #   environment:
  #     - BIND9_USER=root
  #     - TZ=Asia/Kolkata
  #   volumes:
  #     - ./bind9/config:/etc/bind
  #     - ./bind9/cache:/var/cache/bind
  #     - ./bind9/records:/var/lib/bind
  #   networks:
  #     bdCluster:
  #       ipv4_address: 192.168.1.50
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #   restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    hostname: pihole.bdc.home
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    networks:
      bdCluster:
        ipv4_address: 192.168.1.11
        priority: 1000
      ph_bridge:
        ipv4_address: 192.168.100.2
        priority: 900
    volumes:
      - ./pihole/pihole.toml:/etc/pihole/pihole.toml:z
    environment:
      TZ: "Asia/Kolkata"
      FTLCONF_webserver_api_password: "password123"
      FTLCONF_dns_dnssec: 'false'
      FTLCONF_dns_revServers: 'true,192.168.1.0/24,192.168.1.1,bdc.home'
      FTLCONF_dns_listeningMode: 'local'
      FTLCONF_dns_bogusPriv: 'false'
      FTLCONF_dns_domainNeeded: 'false'
      FTLCONF_dns_upstreams: 'unbound.bdc.home#53'
      FTLCONF_debug_api: 'true'
    cap_add:
      - NET_ADMIN

  unbound:
    container_name: unbound
    hostname: unbound.bdc.home
    image: "mvance/unbound:latest"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      bdCluster:
        ipv4_address: 192.168.1.15
    volumes:
      - ./unbound:/opt/unbound/etc/unbound:z
    restart: unless-stopped
