version: '3.8'

networks:
  bdCluster:
    name: bdCluster
    driver: ipvlan
    external: true
    driver_opts:
      parent: ${ETHERNET_NAME}
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

services:

  dn:
    image: dn
  
  jupyter:
    build: 
      dockerfile: ${HOST_DIR}/jupyter/Dockerfile
      args:
        - GIT_DIR=${GIT_DIR}
        - GIT_REMOTE_ADDRESS=${GIT_REMOTE_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - SPARK_VERSION=${SPARK_VERSION}
    user: root
    image: jupyter
    container_name: jupyter
    hostname: jupyter.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.45
    ports:
      - 8091:8091
    volumes:
      - /home/vishesh/notebooks:/root/notebooks
    depends_on:
      - dn