CREATE ROLE hue LOGIN SUPERUSER PASSWORD 'abcd1234' \gexec

SELECT 'CREATE DATABASE bdc' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'bdc')\gexec

GRANT CONNECT ON DATABASE bdc TO hue \gexec

\c bdc \gexec

CREATE SCHEMA IF NOT EXISTS nessie \gexec

CREATE SCHEMA IF NOT EXISTS airflow \gexec

CREATE SCHEMA IF NOT EXISTS logs \gexec

CREATE SCHEMA IF NOT EXISTS hue \gexec

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hue TO hue \gexec
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hue TO hue \gexec
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA hue TO hue \gexec

ALTER DEFAULT PRIVILEGES IN SCHEMA hue GRANT ALL PRIVILEGES ON TABLES TO hue;
ALTER DEFAULT PRIVILEGES IN SCHEMA hue GRANT ALL PRIVILEGES ON SEQUENCES TO hue;

REVOKE ALL ON SCHEMA public FROM public \gexec

