SELECT 'CREATE DATABASE nessie' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'bdc')\gexec

CONNECT bdc \gexec

CREATE SCHEMA IF NOT EXISTS nessie \gexec

CREATE SCHEMA IF NOT EXISTS trino \gexec

CREATE SCHEMA IF NOT EXISTS airflow \gexec

CREATE SCHEMA IF NOT EXISTS hue \gexec

CREATE SCHEMA IF NOT EXISTS logs \gexec
