SELECT 'CREATE DATABASE bdc' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'bdc')\gexec

\c bdc \gexec

CREATE SCHEMA IF NOT EXISTS nessie \gexec

CREATE SCHEMA IF NOT EXISTS airflow \gexec

CREATE SCHEMA IF NOT EXISTS hue \gexec

CREATE SCHEMA IF NOT EXISTS logs \gexec

REVOKE CREATE ON SCHEMA public FROM root \gexec

-- REVOKE USAGE ON SCHEMA public FROM PUBLIC \gexec
