polaris.persistence.type=jdbc
polaris.persistence.jdbc.url=jdbc:postgresql://postgresql.bdc.home:5432/bdc?currentSchema=polaris
polaris.persistence.jdbc.user=root
polaris.persistence.jdbc.password=abcd1234