services:
  hdc:
    build:
      context: ""
      dockerfile: ${HOST_DIR}/baseimage/Dockerfile
      args:
        - JAVA_VER=${JAVA_VER}
        - PY_VER=${PY_VER}
        - DOCKER_USR=${DOCKER_USR}
        - DOCKER_PASS=${DOCKER_PASS}
        - DOCKER_DIR=${DOCKER_DIR}
        - AIRFLOW_VER=${AIRFLOW_VER}
        - SPARK_VERSION=${SPARK_VERSION}
    image: hdc
