version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
  command: server --console-address ":9001" http://minio{1...3}.bdc.home/data
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.101
    volumes:
      - ${LOCAL_DIR}docker/minio-objstrg1:/data
      # - data1-1:/data1
      # - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.102
    volumes:
      - ${LOCAL_DIR}docker/minio-objstrg2:/data
      # - data2-1:/data1
      # - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.103
    volumes:
      - ${LOCAL_DIR}docker/minio-objstrg3:/data
      # - data3-1:/data1
      # - data3-2:/data2

  # minio4:
  #   <<: *minio-common
  #   hostname: minio4
  #   volumes:
  #     - data4-1:/data1
  #     - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      # - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
# volumes:
#   data1-1:
#   data1-2:
#   data2-1:
#   data2-2:
#   data3-1:
#   data3-2:
#   data4-1:
#   data4-2: