version: '3'

services:
  bind9:
    container_name: ldns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: always 