networks:
  bdCluster:
    name: bdCluster
    external: true
    driver: ipvlan
    driver_opts:
      parent: ${ETHERNET_NAME}
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24
          gateway: 192.168.1.1

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:latest
  command: server --console-address ":9001" http://minio{1...3}.bdc.home/data
  expose:
    - "9000"
    - "9001"
  environment:
    TZ: Asia/Kolkata
    MINIO_ROOT_USER: admin
    MINIO_ROOT_PASSWORD: password
    MINIO_REGION: us-east-1
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:    
  minio1:
    <<: *minio-common
    hostname: minio1.bdc.home
    container_name: minio1
    restart: unless-stopped
    networks:
      bdCluster:
        ipv4_address: 192.168.1.101
    volumes:
      - ${LOCAL_DIR}docker/minio:/data

  minio2:
    <<: *minio-common
    hostname: minio2.bdc.home
    container_name: minio2
    restart: unless-stopped
    networks:
      bdCluster:
        ipv4_address: 192.168.1.102
    volumes:
      - ${LOCAL_DIR}docker/minio:/data

  minio3:
    <<: *minio-common
    hostname: minio3.bdc.home
    container_name: minio3
    restart: unless-stopped
    networks:
      bdCluster:
        ipv4_address: 192.168.1.103
    volumes:
      - ${LOCAL_DIR}docker/minio:/data
  
  nginx-lb:
    image: nginx:1.19.2-alpine
    hostname: nginx-lb.bdc.home
    container_name: nginx-lb
    restart: unless-stopped
    networks:
      bdCluster:
        ipv4_address: 192.168.1.91
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"

