version: 2.18.1
services:
  nrsh:
    image: nrsh
  dn:
    image: dn
  name-res:
    build: 
      context: name-res
      dockerfile: ${HOST_DIR}/hdc/name-res/Dockerfile
      args:
        - GIT_DIR=${GIT_DIR}
        - GIT_REMOTE_ADDRESS=${GIT_REMOTE_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_NAMENODE_DIR=${DOCKER_NAMENODE_DIR}
    user: root
    image: name-res
    container_name: name-res
    restart: always
    hostname: name-res
    cpus: 1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 9870:9870
      - 8088:8088
    volumes:
      - hdc:${DOCKER_DIR}hosts
      - ${LOCAL_DIR}${LOCAL_NAMENODE_DIR}:${DOCKER_DIR}${DOCKER_NAMENODE_DIR}
    depends_on:
      - nrsh
  secon-hist:
    build: 
      context: secon-hist
      dockerfile: ${HOST_DIR}/hdc/secon-hist/Dockerfile
      args:
        - GIT_DIR=${GIT_DIR}
        - GIT_REMOTE_ADDRESS=${GIT_REMOTE_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_SECONDARY_NAMENODE_DIR=${DOCKER_SECONDARY_NAMENODE_DIR}
    user: root
    image: secon-hist
    container_name: secon-hist
    restart: always
    hostname: secon-hist
    cpus: 1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 18080:18080
      - 9868:9868
      - 19888:19888
    volumes:
      - hdc:${DOCKER_DIR}hosts
      - ${LOCAL_DIR}${LOCAL_SECONDARY_NAMENODE_DIR}:${DOCKER_DIR}${DOCKER_SECONDARY_NAMENODE_DIR}
    depends_on:
      - name-res
  data-node1:
    build: 
      context: data-node
      dockerfile: ${HOST_DIR}/hdc/data-node/Dockerfile
      args:
        - GIT_DIR=${GIT_DIR}
        - GIT_REMOTE_ADDRESS=${GIT_REMOTE_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_DATANODE_DIR=${DOCKER_DATANODE_DIR}
    user: root
    image: data-node1
    container_name: data-node1
    restart: always
    hostname: data-node1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - hdc:${DOCKER_DIR}hosts
      - ${LOCAL_DIR}${LOCAL_DATANODE_DIR1}:${DOCKER_DIR}${DOCKER_DATANODE_DIR}
    depends_on:
      - name-res
      - dn
  data-node2:
    build: 
      context: data-node
      dockerfile: ${HOST_DIR}/hdc/data-node/Dockerfile
      args:
        - GIT_DIR=${GIT_DIR}
        - GIT_REMOTE_ADDRESS=${GIT_REMOTE_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_DATANODE_DIR=${DOCKER_DATANODE_DIR}
    user: root
    image: data-node2
    container_name: data-node2
    restart: always
    hostname: data-node2
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - hdc:${DOCKER_DIR}hosts
      - ${LOCAL_DIR}${LOCAL_DATANODE_DIR2}:${DOCKER_DIR}${DOCKER_DATANODE_DIR}
    depends_on:
      - data-node1
  postgresql:
    build:
      context: postgresql
      dockerfile: ${HOST_DIR}/hdc/postgresql/Dockerfile
      args:
        - GIT_DIR=${GIT_DIR}
        - GIT_REMOTE_ADDRESS=${GIT_REMOTE_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DB_VER=${DB_VER}
    image: postgresql
    container_name: postgresql
    hostname: postgresql
    cpus: 1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${DOCKER_PASS}
    ports:
      - 5432:5432
    volumes:
      - hdc:${DOCKER_DIR}hosts 
      - ${LOCAL_DIR}${DB_DIR}:/var/lib/postgresql/data
  nessie:
    build:
      context: nessie
      dockerfile: ${HOST_DIR}/hdc/nessie/Dockerfile
      args:
        - DOCKER_USR=${DOCKER_USR}
        - DOCKER_PASS=${DOCKER_PASS}
        - NESSIE_GC_VER=${NESSIE_GC_VER}
    image: nessie
    container_name: nessie
    hostname: nessie
    restart: always
    ports:
      - 19120:19120
    volumes:
      - hdc:/home/jboss/hosts
    depends_on:
      - postgresql
volumes:
  hdc:

  #mysql:
  #  build:
  #    context: mysql
  #    dockerfile: /home/vishesh/docker/hdc/mysql/Dockerfile
  #    args:
  #      - GIT_DIR=${GIT_DIR}
  #      - GIT_REMOTE_ADDRESS=${GIT_REMOTE_ADDRESS}
  #      - DOCKER_DIR=${DOCKER_DIR}
  #      - MYSQL_VER=${MYSQL_VER}
  #      - MYSQL_DIR=${MYSQL_DIR}
  #  user: root
  #  image: mysql
  #  container_name: mysql
  #  hostname: mysql
  #  sysctls:
  #    - net.ipv6.conf.all.disable_ipv6=0
  #  environment:
  #    MYSQL_ROOT_PASSWORD: $DOCKER_PASS
  #  volumes:
  #    - hdc:${DOCKER_DIR}hosts
  #    - ${LOCAL_DIR}$MYSQL_DIR:/var/lib/mysql
  #  ports:
  #    - 3306:3306
  #  depends_on:
  #    - hdc_baseimage
  #hue:
  # build:
  #     context: hue
  #     dockerfile: /home/vishesh/docker/hdc/hue/Dockerfile
  #     args:
  #       - OS_VER=${OS_VER}
  #       - HUE_VER=${HUE_VER}
  #       - GIT_DIR=${GIT_DIR}
  #       - GIT_REMOTE_ADDRESS=${GIT_REMOTE_ADDRESS}
  #       - DOCKER_DIR=${DOCKER_DIR}
  # image: hue
  # hostname: hue
  # container_name: hue
  # ports:
  # - 8888:8888
  # volumes:
  #   - hdc:${DOCKER_DIR}/hosts
  #   #- ./hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
  # depends_on 
  #    - mariadb