version: '3.8'

networks:
  bdCluster:
    name: bdCluster
    driver: ipvlan
    driver_opts:
      parent: ${ETHERNET_NAME}
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          

services:
  hdc:
    image: hdc
    
  name-res:
    build: 
      context: name-res
      dockerfile: ${HOST_DIR}/hdc/name-res/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - GIT_AIRFLOW_ADDRESS=${GIT_AIRFLOW_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_NAMENODE_DIR=${DOCKER_NAMENODE_DIR}
        - LOCAL_NAMENODE_DIR=${LOCAL_NAMENODE_DIR}
    user: root
    image: name-res
    container_name: name-res
    restart: unless-stopped
    hostname: name-res.bdc.home
    cpus: 1
    networks:
      bdCluster:
        ipv4_address: 192.168.1.41
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 9870:9870
      - 8088:8088
    volumes:
      - ${LOCAL_DIR}${LOCAL_NAMENODE_DIR}:${DOCKER_DIR}${DOCKER_NAMENODE_DIR}
      - ${DOCKER_DIR}logs/namenode1:${DOCKER_DIR}logs/hadoop
      - ${DOCKER_DIR}hadoop:${DOCKER_DIR}hadoop:ro
      - /root/${AIRFLOW_DIR}:/root/${AIRFLOW_DIR}
    depends_on:
      - hdc

  secon-hist:
    build: 
      context: secon-hist
      dockerfile: ${HOST_DIR}/hdc/secon-hist/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_SECONDARY_NAMENODE_DIR=${DOCKER_SECONDARY_NAMENODE_DIR}
    user: root
    image: secon-hist
    container_name: secon-hist
    restart: unless-stopped
    hostname: secon-hist.bdc.home
    cpus: 1
    networks:
      bdCluster:
        ipv4_address: 192.168.1.42
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 18080:18080
      - 9868:9868
      - 19888:19888
    volumes:
      - ${LOCAL_DIR}${LOCAL_SECONDARY_NAMENODE_DIR}:${DOCKER_DIR}${DOCKER_SECONDARY_NAMENODE_DIR}
      - ${DOCKER_DIR}logs/secondary:${DOCKER_DIR}logs/hadoop
      - ${DOCKER_DIR}hadoop:${DOCKER_DIR}hadoop:ro
    depends_on:
      - hdc

  data-node1:
    build: 
      context: data-node
      dockerfile: ${HOST_DIR}/hdc/data-node/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - GIT_AIRFLOW_ADDRESS=${GIT_AIRFLOW_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_DATANODE_DIR=${DOCKER_DATANODE_DIR}
    user: root
    image: data-node1
    container_name: data-node1
    restart: unless-stopped
    hostname: data-node1.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.51
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ${LOCAL_DIR}${LOCAL_DATANODE_DIR1}:${DOCKER_DIR}${DOCKER_DATANODE_DIR}
      - ${DOCKER_DIR}logs/data-node1:${DOCKER_DIR}logs/hadoop
      - ${DOCKER_DIR}hadoop:${DOCKER_DIR}hadoop:ro
      - ${DOCKER_DIR}spark:${DOCKER_DIR}spark:ro
      - /root/${AIRFLOW_DIR}:/root/${AIRFLOW_DIR}
    depends_on:
      - hdc

  data-node2:
    build: 
      context: data-node
      dockerfile: ${HOST_DIR}/hdc/data-node/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - GIT_AIRFLOW_ADDRESS=${GIT_AIRFLOW_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_DATANODE_DIR=${DOCKER_DATANODE_DIR}
    user: root
    image: data-node2
    container_name: data-node2
    restart: unless-stopped
    hostname: data-node2.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.52
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ${LOCAL_DIR}${LOCAL_DATANODE_DIR2}:${DOCKER_DIR}${DOCKER_DATANODE_DIR}
      - ${DOCKER_DIR}logs/data-node2:${DOCKER_DIR}logs/hadoop
      - ${DOCKER_DIR}hadoop:${DOCKER_DIR}hadoop:ro
      - ${DOCKER_DIR}spark:${DOCKER_DIR}spark:ro
      - /root/${AIRFLOW_DIR}:/root/${AIRFLOW_DIR}
    depends_on:
      - hdc
  
  