version: "3.8"

networks:
  bdCluster:
    name: bdCluster
    driver: ipvlan
    driver_opts:
      parent: ${ETHERNET_NAME}
    ipam:
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.0/24
          gateway: 192.168.1.1

volumes:
  cifs-volume:
    driver_opts:
      type: cifs
      o: nounix,rw
      device: //worker1.bdc.home/airflow

services:
  hdc:
    build:
      context: "../baseimage/"
      dockerfile: Dockerfile
      args:
        - JAVA_VER=${JAVA_VER}
        - PY_VER=${PY_VER}
        - DOCKER_USR=${DOCKER_USR}
        - DOCKER_PASS=${DOCKER_PASS}
        - DOCKER_DIR=${DOCKER_DIR}
        - AIRFLOW_VER=${AIRFLOW_VER}
        - SPARK_VERSION=${SPARK_VERSION}
    image: hdc

  name-res:
    build:
      context: name-res
      dockerfile: ${HOST_DIR}/hdc/name-res/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - GIT_AIRFLOW_ADDRESS=${GIT_AIRFLOW_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_NAMENODE_DIR=${NAMENODE_DIR}
        - LOCAL_NAMENODE_DIR=${NAMENODE_DIR}
    user: root
    image: name-res
    container_name: name-res
    restart: unless-stopped
    hostname: name-res.bdc.home
    cpus: 1
    networks:
      bdCluster:
        ipv4_address: 192.168.1.91
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 192.168.1.11:9870:9870
      - 192.168.1.11:8088:8088
    volumes:
      - ${LOCAL_DIR}${NAMENODE_DIR}:${DOCKER_DIR}${NAMENODE_DIR}
      # - ${LOCAL_DIR}logs/namenode1:${DOCKER_DIR}logs/hadoop
      - ${LOCAL_DIR}hadoop:${DOCKER_DIR}hadoop:ro
      - cifs-volume:/root/${AIRFLOW_DIR}:z
    depends_on:
      - hdc

  secon-hist:
    build:
      context: secon-hist
      dockerfile: ${HOST_DIR}/hdc/secon-hist/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - SECONDARY_NAMENODE_DIR=${SECONDARY_NAMENODE_DIR}
    user: root
    image: secon-hist
    container_name: secon-hist
    restart: unless-stopped
    hostname: secon-hist.bdc.home
    cpus: 1
    networks:
      bdCluster:
        ipv4_address: 192.168.1.94
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 18080:18080
      - 9868:9868
      - 19888:19888
    volumes:
      - ${LOCAL_DIR}${SECONDARY_NAMENODE_DIR}:${DOCKER_DIR}${SECONDARY_NAMENODE_DIR}
      # - ${DOCKER_DIR}logs/secondary:${DOCKER_DIR}logs/hadoop
      - ${DOCKER_DIR}hadoop:${DOCKER_DIR}hadoop:ro
    depends_on:
      - hdc

  data-node1:
    build:
      context: data-node
      dockerfile: ${HOST_DIR}/hdc/data-node/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - GIT_AIRFLOW_ADDRESS=${GIT_AIRFLOW_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_DATANODE_DIR=${DATANODE_DIR}
    user: root
    image: data-node
    container_name: data-node1
    restart: unless-stopped
    hostname: data-node1.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.101
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ${LOCAL_DIR}${DATANODE_DIR}1:${DOCKER_DIR}${DATANODE_DIR}
      # - ${DOCKER_DIR}logs/data-node1:${DOCKER_DIR}logs/hadoop
      - ${DOCKER_DIR}hadoop:${DOCKER_DIR}hadoop:ro
      - ${DOCKER_DIR}spark:${DOCKER_DIR}spark:ro
      - cifs-volume:/root/${AIRFLOW_DIR}:z
    depends_on:
      - hdc

  data-node2:
    build:
      context: data-node
      dockerfile: ${HOST_DIR}/hdc/data-node/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - GIT_AIRFLOW_ADDRESS=${GIT_AIRFLOW_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_DATANODE_DIR=${DATANODE_DIR}
    user: root
    image: data-node
    container_name: data-node2
    restart: unless-stopped
    hostname: data-node2.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.102
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ${LOCAL_DIR}${DATANODE_DIR}2:${DOCKER_DIR}${DATANODE_DIR}
      # - ${DOCKER_DIR}logs/data-node2:${DOCKER_DIR}logs/hadoop
      - ${DOCKER_DIR}hadoop:${DOCKER_DIR}hadoop:ro
      - ${DOCKER_DIR}spark:${DOCKER_DIR}spark:ro
      - cifs-volume:/root/${AIRFLOW_DIR}:z
    depends_on:
      - hdc

  data-node3:
    build:
      context: data-node
      dockerfile: ${HOST_DIR}/hdc/data-node/Dockerfile
      args:
        - GIT_CONFIG_DIR=${GIT_CONFIG_DIR}
        - GIT_CONFIG_ADDRESS=${GIT_CONFIG_ADDRESS}
        - GIT_AIRFLOW_ADDRESS=${GIT_AIRFLOW_ADDRESS}
        - DOCKER_DIR=${DOCKER_DIR}
        - DOCKER_DATANODE_DIR=${DATANODE_DIR}
    user: root
    image: data-node
    container_name: data-node3
    restart: unless-stopped
    hostname: data-node3.bdc.home
    networks:
      bdCluster:
        ipv4_address: 192.168.1.103
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ${LOCAL_DIR}${DATANODE_DIR}3:${DOCKER_DIR}${DATANODE_DIR}
      # - ${DOCKER_DIR}logs/data-node2:${DOCKER_DIR}logs/hadoop
      - ${DOCKER_DIR}hadoop:${DOCKER_DIR}hadoop:ro
      - ${DOCKER_DIR}spark:${DOCKER_DIR}spark:ro
      - cifs-volume:/root/${AIRFLOW_DIR}:z
    depends_on:
      - hdc
