acl internal {
    192.168.1.0/24;
};

options {
    forwarders {
        1.1.1.1;
    };
    allow-query {
        internal;
    };
};

zone "bdc.home" IN {
    type master;
    file "/etc/bind/bd-cluster-home.zone";

};

zone "1.168.192.in-addr.arpa" IN {
    type master;
    file "/etc/bind/rbd-cluster-home.zone";
};

key "bdc.home" {
    algorithm hmac-sha512;
    secret "951e55ab45eced7824a66be6c91c3214b6ef31ad4143a6f2aa9766aeb53a3da019392cc574c2a3f3d119266f81f7d67c463528b5be6c924f77691776819b8d18";
};
